name: Just Testing
on:
  workflow_dispatch:
 
jobs:
  flutter_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python test1.py
        id: test1
      - run: python test2.py
        env: 
          LINK : ${{ steps.test1.outputs }}