name: Pull Github Merged file
on:
  workflow_dispatch:
    # inputs:
    #   token:
    #     description: 'token'
    #     required: true
    #     default: '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'
    #     type: string
    # branches:
    #   - main
jobs:
  flutter_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      - name: upload APK to Google Drive
        env:
          OAUTH_GOOGLE : ${{ secrets.OAUTH_GOOGLE }}
        id: gdrive
        run: python .github/workflows/uploadGdrive.py
      - name: notif Teams
        env:
          LINK_GDRIVE : ${{ steps.gdrive.outputs }}
        run: action.py
  # post_issues_on_Teams:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3.3.0
      # - name: Run Python Script
      #   run: python .github/workflows/action.py
        # env:
        #   SLACK_BOT_TOKEN : ${{ secrets.SLACK_BOT_TOKEN }}


